services:
  db:
    container_name: actioncable-db
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    container_name: actioncable-web
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: app_development
      DATABASE_NAME_TEST: app_test
    depends_on:
      - db
volumes:
  postgres_data:
