services:
  db:
    container_name: actioncable-db
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    container_name: actioncable-web
    build:
      context: .
      args:
        RUBY_VERSION: 3.2.7
    environment:
      RAILS_ENV: production
      DATABASE_HOST: db
      DATABASE_USERNAME: ${POSTGRES_USER:-app}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME:-app_production}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    command: "./bin/rails server"
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  postgres_data:
