services:
  db:
    container_name: actioncable-db
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    container_name: actioncable-web
    build:
      context: .
      args:
        RUBY_VERSION: 3.2.7
    environment:
      RAILS_ENV: ${RAILS_ENV:-development}
      DATABASE_HOST: db
      DATABASE_USERNAME: ${POSTGRES_USER:-postgres}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD:-password}
      DATABASE_NAME: ${DATABASE_NAME:-app_development}
      DATABASE_NAME_TEST: ${DATABASE_NAME_TEST:-app_test}
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  postgres_data:
